<!-- START CONTAINER FLUID -->
<style>
body{font-family:arial}
p,div,i,span,h1,h2,h3,h4,h5,h6,b,table,td,th{padding:0;margin:0}
.header{background:#ebebeb none repeat scroll 0 0;border-radius:3px;float:left;margin-bottom:20px;padding:15px 2%;width:96%}
.top-head{float:left;margin-bottom:19px;text-align:center;width:100%}
.top-head h2{color:#077ed0;font-size:20px;margin:0;padding:0}
.top-head > p{color:#626262;font-size:14px;margin:0;padding-top:3px}
.after-head{float:left;width:100%}
.svehicle{margin-right:15px}
.uppder-cont{float:left;width:100%}
.invoice{background: #ebebeb none repeat scroll 0 0;
    border-radius: 3px;
    float: left;
    padding: 2%;
    width: 96%;}
table.top-tab-bar{border:1px solid #dedede;float:left;margin:0;padding:0;width:100%}
table.top-tab-bar th{background:#077ed0 none repeat scroll 0 0;color:#fff;text-transform:uppercase}
.lth{width:345px}
table.top-tab-bar th,table.top-tab-bar td{font-size:12px;padding:13px 10px;text-align:left}
table.top-tab-bar td.text-center,table.top-tab-bar th.text-center{text-align:center}
.vth{width:100px}
.inner-thead th:nth-child(7), .inner-thead td:nth-child(7) {
  text-align: center;
  width: 63px;
}
table.ttable{background: #fff none repeat scroll 0 0;
    border-radius: 0px;
    box-shadow: 0 0 0 rgba(0, 0, 0, 0.42);
    -moz-box-shadow: 0 0 0 rgba(0, 0, 0, 0.42);
    -webkit-box-shadow: 0 0 0 rgba(0, 0, 0, 0.42);
    -o-box-shadow: 0 0 0 rgba(0, 0, 0, 0.42);
    float: none;
    margin: 0 auto;
    padding: 10px 20px;
    width: 100%;}
table.ttable .tb-3-block tr td.slabel{font-weight:700;font-size:12px;width:30%;}
table.ttable .tb-3-block tr td.stext{color:#626464;font-size:12px;width:60%;}
table.theadtable tr td{text-align: center;}
table.theadtable {width: 100%; }
.tb-3-block {
  width: 100%;
}
table.theadtable tr td.h2{color:#077ed0;font-size:20px;margin:0;padding:0; font-weight: bold;}
table.theadtable tr td.p{color:#626262;font-size:12px;margin:0;padding-top:3px}
table.ttable tr td {
    padding: 5px 0;
}
.ttable .tb-3-block td:nth-child(2n) {
    padding-right: 10px;width:10%;
}
.invoice table {
  background: #fff none repeat scroll 0 0;
  float: left;
  margin: 0;
  overflow: hidden;
  padding: 0;
  width: 100%;
}
.driver-table h3 {
  margin-bottom: 10px; color: rgb(85, 85, 85);
}
table.driver-table tr:nth-child(2n) {
  background: rgba(0, 0, 0, 0) none repeat scroll 0 0;
}
table.inner-thead tr:nth-child(2n) {
  background:rgba(241, 241, 241,0.4) none repeat scroll 0 0;
}
table .driver-table td, table .driver-table th {
  padding: 13px 0;
}
table .driver-table td table td, table .driver-table td  table th{
  padding: 13px 10px; 
}
 table .driver-table td  table td{
   color: rgb(85, 85, 85);
}
.top-tab-bar h2 {
  border-bottom: 1px solid rgb(222, 222, 222);
  padding-bottom: 12px;
}
.individual .twf_1 {
  width: 45px;
}
.individual .twf_9 {
  text-align: center;
  width: 67px;
}
.twf_4, .twf_1, .twf_5, .twf_6, .twf_7, .twf_8, .twf_9, .twf_10, .twf_11, .twf_14, .twf_16, .twf_17, .twf_19 {
  text-align: center;
}
.twf_1{width:60px;}
.Performance .twf_2, .Performance .twf_3 {
  text-align: center;
}
.Individual .twf_13 {
    text-align: center;
}
.Individual .twf_2, .Individual .twf_3, .Individual .twf_12, .Individual .twf_14 {
    text-align: left;
}
</style>

<!-- START CONTAINER FLUID -->
<div class="container-fluid container-fixed-lg">
    <!-- START PANEL -->
    <div class="panel panel-default">
        <div class="panel-body">
        	<div class="uppder-cont">
				<!--top-block-->
				<div style="padding-bottom:20px;width:100%; float:left;">
					<div style="background:#EBEBEB;padding:2%;width:96%;float:left;">
						<h2 style="color: #077ed0;font-size: 20px;font-weight: bold; margin: 0;padding: 0;text-align: center;width:100%;"><?php echo strtoupper($report['title']); ?></h2>
						<p style="padding-bottom:10px; color: #626262;font-size: 12px;margin: 0;padding-top: 3px;text-align: center;float:left;width:100%;"><?php echo $report['context']; ?></p>
						<div style=" background: #fff none repeat scroll 0 0; border-radius: 0;  box-shadow: 0 0 0 rgba(0, 0, 0, 0.42);   margin: 0 auto;  padding: 15px 2%;width: 96%;float:left;">
							<div style="width:33.33%;float:left;">
								<div style=" font-size: 12px;font-weight: 700;width: 30%;float:left;">Scope</div>
								<div style="padding-right: 10px; width: 10%;float:left;">:</div>
								<div style="color: #626464;  font-size: 12px; width: 56%; float:left;"><?php echo empty(ucfirst($args["scope"])) ? "All Groups" : ucfirst($args["scope"]) ; ?></div>
							</div>
							<div style="width:33.33%;float:left;">
								<div style=" font-size: 12px;font-weight: 700;width: 30%;float:left;">Generated By  </div>
								<div style="padding-right: 10px; width: 10%;float:left;">:</div>
								<div style="color: #626464;  font-size: 12px; width: 56%; float:left;"><?php echo ucfirst($byuser); ?></div>
							</div>
							<div style="width:33.33%;float:left;">
								<div style=" font-size: 12px;font-weight: 700;width: 30%;float:left;">Report Type</div>
								<div style="padding-right: 10px; width: 10%;float:left;">:</div>
								<div style="color: #626464;  font-size: 12px; width: 56%; float:left;">
									<?php  echo ucfirst($args["reportType"]); ?>
								</div>
							</div>
						</div>
					</div>
				</div>
				<!--top-block end-->
				<!--table-block-->
				<div class="<?php echo ucfirst($args["reportType"]);?>" style="background: #ebebeb none repeat scroll 0 0; border-radius: 3px;  float: left;  padding: 2%; width: 96%;">
					<?php  
						if(is_array($result_t) && count($result_t) > 0){
							foreach ($result_t as $key => $dList) { ?>
								<div style="background: #fff none repeat scroll 0 0;  float: left; margin: 0;  overflow: hidden;  padding: 0;  width: 98%;padding:1%;">
									<h2 style="border-bottom: 1px solid rgb(222, 222, 222);  padding-bottom: 12px;  font-size: 18px;margin-bottom:15px;"><span>Dispatcher : </span><?php echo $key; ?></h2>
									<?php foreach($dList as $dlkey => $driverList) { ?>
									<!-- block-repeat-->
									<div style="width:100%;float:left;">
										
										<div style="width:100%;float:left;margin-bottom:20px;">
										<?php if ( $args['scope'] == 'all' && $args['reportType'] == 'performance'){ ?>

											<table class="inner-thead" cellpadding="0" cellspacing="0" style="   width: 100%;">
												<thead>
													<tr style=" background: #077ed0">
													  <?php 
														$i=1;
														foreach ($column_mappings as $key => $value) { 
														  if(strtolower($value) == "dispatcher"){
															  continue;
														  }
															$class = "twf_".$i++;
														?>
															<th style="white-space: nowrap;border:none;  color: #fff; text-transform: uppercase;font-size:11px;padding: 13px 10px;" class="text-center <?php echo $class; ?>" ><?php echo $value; ?></th>
													  <?php	} ?>
													</tr>
												</thead>
												<tbody>
											  		<tr>
													<?php 
														foreach($driverList as $rkey => $row){
														$j = 1;?>
														<td style=" none repeat scroll 0 0;   color: rgb(85, 85, 85); text-transform: uppercase;font-size:11px;padding: 13px 10px;" class="twf_<?php echo $j++; ?>">
															<?php echo $row; ?>
															<?php echo $rkey == "overallTotalProfitPercent" ? "%" : ""; ?>
														</td>
													<?php } ?>
													 </tr>
												</tbody>
											</table>



										<?php } else { ?>
										  	<table class="inner-thead" cellpadding="0" cellspacing="0" style="   width: 100%;">
										  	<caption style="text-align: left;width: 100%;padding: 0;margin: 0;"><h3 style="color: rgb(85, 85, 85);margin-bottom: 10px;width:100%;float:left;font-size:14px;"><span>Driver : </span><?php echo $dlkey; ?></h3></caption>
												<thead>
													<tr style=" background: #077ed0">
													  <?php 
														$i=1;
														foreach ($column_mappings as $key => $value) { 
														  if(strtolower($value) == "dispatcher"){
															  continue;
														  }
															$class = "twf_".$i++;
														?>
															<th style="white-space: nowrap;border:none;  color: #fff; text-transform: uppercase;font-size:11px;padding: 13px 10px;" class="text-center <?php echo $class; ?>" ><?php echo $value; ?></th>
													  <?php	} ?>
													</tr>
												</thead>
												<tbody>
												<?php 

												foreach($driverList as $rkey => $row){
													$j = 1;?>
												  <tr>
													<?php foreach( $row as $ckey => $cols) { ?>
													<td style=" none repeat scroll 0 0;   color: rgb(85, 85, 85); text-transform: uppercase;font-size:11px;padding: 13px 10px;" class="twf_<?php echo $j++; ?>">
														<?php echo $cols; ?>
														<?php echo $ckey == "overallTotalProfitPercent" ? "%" : ""; ?>
													</td>
													<?php } ?>
												  </tr>
												<?php } ?>
												</tbody>	
											</table>

										<?php } ?>

										</div>
									</div><!-- block-repeat-->
									<?php }?>
									
								</div>
							<?php } 
						}?>
				</div>
				<!--table-block-end-->
        	</div> <!--uppder-cont  -->
    	</div><!-- panel-body -->
    </div><!-- END PANEL -->
</div>    	


<!-- END CONTAINER FLUID -->
